name: PR Check

on:
  pull_request:
    branches: [ development, staging, production ]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Check syntax
      run: |
        php -l src/botManager.php
        php -l src/index.php
        
    - name: Check for secrets
      run: |
        if grep -r "BOT_TOKEN\|WEBHOOK_CODE\|CHAT_ID" src/; then
          echo "❌ Secrets found in source code!"
          exit 1
        else
          echo "✅ No secrets in source code"
        fi
        
    - name: Check configuration
      run: |
        if [ -f "config/config.example.php" ]; then
          echo "✅ Config example exists"
        else
          echo "❌ Config example missing"
          exit 1
        fi
